### PR TITLE
Improve script.

### PR DESCRIPTION
**Pull request by wizonesolutions**
I'm using this with the new experience on JIRA and hit a few issues. I'm just sending one PR since it's a small project, but I can split them up if it's too confusing. Hope you find it useful.

- Optional Docker Compose file added.
- Added jiraLoginUsername for JIRA Cloud users that log in with Atlassian ID
but have a different username in the instance.
- Added notifyUsers option to silence emails when syncing time.
Defaults to TRUE, so behavior is not changed.

### CODE REVIEW

**Comment by AxaliaN** [comment]
Hiya, first of all, thanks for contributing :) I am happy to merge this, unfortunately, the unit tests are failing and there are some code style issues (see Scrutinizer).

If you fix them, this can be merged.

**Comment by wizonesolutions** [comment]
Ah, I configured PhpStorm for Zend, but there wasn't an `.editorconfig`, so I wasn't sure of the actual style in use :) I'll fix the boolean case later today when I run the script again and try to get the tests passing. I assume I have to update them to be aware of the new parameters/properties.

**Comment by wizonesolutions** [comment]
I think it should be all good now :)

**Comment by AxaliaN** [comment]
Yay! Merged and thanks :)

**Pull request merged**
